name:                pixlytypo
version:             0.1.0.0
author:              "Claes-Magnus Berg"
maintainer:          "claes-magnus@herebeseaswines.net"
copyright:           "MIT"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  pixlytypo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pixlytypo
